---
##############################################################################
# Iris Configuration
##############################################################################
iris:
  url: "https://pyris-test.artemis.cit.tum.de"
  secret: "{{ lookup('hashi_vault', 'artemis/data/test/artemistestcommon').get('iris_secret') }}"

artemis_local_llm_deployment_enabled: true
