---
is_testserver: false

artemis_database_dbname: "Artemis"
artemis_database_username: "Artemis"

artemis_internal_admin_user: artemis_admin

artemis_repo_basepath: "/mnt/storage"
artemis_legal_path: "/mnt/storage/legal"
artemis_data_export_path: "/mnt/storage/data-exports"
artemis_tmp_directory: "/opt/artemis/tmp"

artemis_ssh_priv_key_value: "none"

artemis_operator_name: "Technical University of Munich"
artemis_operator_admin_name: "Stephan Krusche"

artemis_database_password: "{{ lookup('hashi_vault', 'kv/data/artemis/' + var_vault_group).get('db_password') }}"
artemis_remote_admin_database_password: "{{ lookup('hashi_vault', 'kv/data/artemis/' + var_vault_group).get('db_remoteadmin_password') }}"
artemis_remote_admin_ro_database_password: "{{ lookup('hashi_vault', 'kv/data/artemis/' + var_vault_group).get('db_remoteadmin_ro_password') }}"

artemis_internal_admin_password: "{{ lookup('hashi_vault', 'kv/data/artemis/' + var_vault_group).get('internal_admin') }}"

##############################################################################
# External Systems Configuration
##############################################################################

lti:
  oauth_secret: "{{ lookup('hashi_vault', 'kv/data/artemis/' + var_vault_group).get('lti_secret') }}"

ldap:
  url: "{{ lookup('hashi_vault', 'kv/data/artemis/common/ldap').get('ldap_url') }}"
  user_dn: "{{ lookup('hashi_vault', 'kv/data/artemis/common/ldap').get('ldap_dn') }}"
  base: "{{ lookup('hashi_vault', 'kv/data/artemis/common/ldap').get('ldap_base') }}"
  password: "{{ lookup('hashi_vault', 'kv/data/artemis/common/ldap').get('ldap_password') }}"

mail:
  hostname: "{{ lookup('hashi_vault', 'kv/data/artemis/common/mail').get('mail_host') }}"
  port: "587"
  username: "{{ lookup('hashi_vault', 'kv/data/artemis/common/mail').get('mail_user') }}"
  password: "{{ lookup('hashi_vault', 'kv/data/artemis/common/mail').get('mail_password') }}"
  protocol: "smtp"
  ssl_trust: "postout.lrz.de"

version_control:
  localvc:
    url: "{{ artemis_server_url }}"
    repo_storage_base_path: /mnt/storage/localvc
    ssh_key_path: /mnt/storage/ssh-keys
    build_agent_use_ssh: true
    ssh_url: "{{ var_artemis_localvc_ssh_url }}"

artemis_ssh_key_path: "/tmp"

apollon_url: "https://apollon.ase.in.tum.de"

iris:
  url: "{{ lookup('hashi_vault', 'kv/data/artemis/common/iris').get('url') }}"
  secret: "{{ lookup('hashi_vault', 'kv/data/artemis/common/iris').get('secret') }}"
  rate_limit: 25
  rate_limit_timeframe_hours: 3

post_hog:
  host: "{{ lookup('hashi_vault', 'kv/data/artemis/common/post_hog').get('url') }}"
  token: "{{ lookup('hashi_vault', 'kv/data/artemis/common/post_hog').get('secret') }}"

enable_science_event_logging: true

atlas:
# More configuration options will be added here in the future

artemis_hyperion_enabled: true

spring_ai:
  azure_openai:
    api_key: "{{ lookup('hashi_vault', 'kv/data/artemis/common/hyperion').get('azure_openai_api_key') }}"
    endpoint: "{{ lookup('hashi_vault', 'kv/data/artemis/common/hyperion').get('azure_openai_endpoint') }}"
    deployment_name: "{{ lookup('hashi_vault', 'kv/data/artemis/common/hyperion').get('azure_openai_deployment_name') }}"
    temperature: 1.0

##############################################################################
# Broker and Registry Configuration
##############################################################################

is_multinode_install: true

broker:
  url: "[fcfe:0:0:0:0:0:b:1]" # Broker hostname (Only used in the Artemis role)
  username: "{{ lookup('hashi_vault', 'kv/data/artemis/' + var_vault_group).get('broker_user') }}"
  password: "{{ lookup('hashi_vault', 'kv/data/artemis/' + var_vault_group).get('broker_password') }}"

registry:
  url: "[fcfe:0:0:0:0:0:b:2]" # Registry hostname (Only used in the Artemis role)

artemis_jhipster_jwt: "{{ lookup('hashi_vault', 'kv/data/artemis/' + var_vault_group).get('jhipster_jwt') }}"
artemis_jhipster_registry_password: "{{ lookup('hashi_vault', 'kv/data/artemis/' + var_vault_group).get('registry_password') }}"
artemis_eureka_instance_id: "{{ node_id }}"

##############################################################################
# Sentry Configuration
##############################################################################
sentry:
  dsn: https://e52d0b9b6b61769f50b088634b4bc781@sentry.aet.cit.tum.de/2
  environment: prod
  enable_db_tracing: true
  traces_sample_rate: 0.2
  send_default_pii: true

##############################################################################
# Deployment User
##############################################################################

artemis_create_deployment_user: true
artemis_deployment_user_name: deployment
artemis_deployment_user_uid: 1338
artemis_deployment_user_public_key: "{{ lookup('hashi_vault', 'kv/data/artemis/' + var_vault_group).get('ssh_pub') }}"
artemis_deployment_user_comment: "User to deploy artemis to this host"


##############################################################################
# Other Configuration
##############################################################################

# Lower the entropy bits to fix a bug with TSAN and MSAN C exercises
entropy_bits_override: 30
