---
##############################################################################
# Commonly changed variables
##############################################################################
var_testserver_name: "artemis-test4"
artemis_database_password: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest4').get('db_password') }}"
artemis_internal_admin_password: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest4').get('internal_admin') }}"
artemis_jhipster_jwt: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest4').get('jhipster_jwt') }}"

weaviate_collection_prefix: "Artemis_ts4_"

llm_api_key: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest4').get('llm_api_key') }}"

artemis_deployment_user_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOod/IHvX1JHG6nySMt5FuuwYYFOU580iuWVctNl5jTZ artemis@xcit.tum.de"
