---
##############################################################################
# Commonly changed variables
##############################################################################
var_testserver_name: "artemis-test5"
artemis_database_password: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest5').get('db_password') }}"
artemis_internal_admin_password: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest5').get('internal_admin') }}"
artemis_jhipster_jwt: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest5').get('jhipster_jwt') }}"

weaviate_collection_prefix: "Artemis_ts5_"

llm_api_key: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest5').get('llm_api_key') }}"

artemis_deployment_user_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFKhFJttVdTqQZggl7zK7aj7dVI7zMzKip7mPq8KQW7u artemis@xcit.tum.de"
