---
##############################################################################
# Commonly changed variables
##############################################################################
var_testserver_name: "artemis-test1"
artemis_database_password: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest1').get('db_password') }}"
artemis_internal_admin_password: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest1').get('internal_admin') }}"
artemis_jhipster_jwt: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest1').get('jhipster_jwt') }}"

weaviate_collection_prefix: "Artemis_ts1_"

athena:
  url: "https://athena-test1.aet.cit.tum.de"
  secret: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest1').get('athena_secret') }}"

llm_api_key: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest1').get('llm_api_key') }}"

artemis_deployment_user_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPzNt4anymci0c4G1wg6welnZj4T9fj8T5wN0bn+g0hH artemis@xcit.tum.de"
