---
##############################################################################
# Weaviate Configuration (test servers)
##############################################################################
weaviate:
  enabled: true
  http_host: weaviate-test.aet.cit.tum.de
  http_port: 443
  grpc_port: 50051
  scheme: https
  collection_prefix: "{{ weaviate_collection_prefix }}"
  vectorizer_module: text2vec-openai
  open_ai_embedding_model: "Qwen/Qwen3-Embedding-8B"
  open_ai_base_url: https://logos.aet.cit.tum.de:8080/
  gpu_api_key: "{{ lookup('hashi_vault', 'kv/data/artemis/common/logos').get('test_api_key') }}"
  api_key: "{{ lookup('hashi_vault', 'kv/data/itg/services/services_ase/weaviate-test').get('api_key') }}"
