---
##############################################################################
# TUM Ldap Configuration
##############################################################################
ldap:
  url: "ldaps://iauth.tum.de:636"
  user_dn: "cn=TUINI01-Artemis,ou=bindDNs,ou=iauth,dc=tum,dc=de"
  base: "ou=users,ou=data,ou=prod,ou=iauth,dc=tum,dc=de"
  password: "{{ lookup('hashi_vault', 'artemis/data/test/artemistestcommon').get('ldap_password') }}"
