---
##############################################################################
# Commonly changed variables
##############################################################################
var_testserver_name: "artemis-test3"
artemis_database_password: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest3').get('db_password') }}"
artemis_internal_admin_password: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest3').get('internal_admin') }}"
artemis_jhipster_jwt: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest3').get('jhipster_jwt') }}"

weaviate_collection_prefix: "Artemis_ts3_"

athena:
  url: "https://athena-test1.aet.cit.tum.de"
  secret: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest3').get('athena_secret') }}"

llm_api_key: "{{ lookup('hashi_vault', 'artemis/data/test/artemistest3').get('llm_api_key') }}"

artemis_deployment_user_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOXQAXj0z1LeGPRicBYgs2//FuSS7eW6cdiJpft9JnbT artemis@xcit.tum.de"
