---
artemis_server_url: "https://artemis-staging-localci.artemis.cit.tum.de"

artemis_version: 7.10.5

var_vault_group: "test/staging-localci"

var_artemis_localvc_ssh_url: "ssh://git@artemis-staging-integrated-code-lifecycle.artemis.cit.tum.de:7921/"

registry_external_host: artemis-staging-localci-registry.artemis.cit.tum.de

artemis_passkey_enabled: true

is_testserver: true

##############################################################################
# External Systems Configuration
##############################################################################

artemis_email: artemis-staging.dse@xcit.tum.de

athena:
  url: "{{ lookup('hashi_vault', 'kv/data/artemis/common/athena-staging').get('url') }}"
  secret: "{{ lookup('hashi_vault', 'kv/data/artemis/common/athena-staging').get('secret') }}"
  restricted_modules: "{{ lookup('hashi_vault', 'kv/data/artemis/common/athena-staging').get('restricted_modules') }}"

##############################################################################
# Proxy Configuration
##############################################################################

proxy_generate_dh_param: false

servers:
  - name: "artemis-staging-localci.artemis.cit.tum.de"
    ssl_certificate_path: /var/lib/rbg-cert/live/host:f:artemis-staging-localci-proxy.artemis.cit.tum.de.fullchain.pem
    ssl_certificate_key_path: /var/lib/rbg-cert/live/host:f:artemis-staging-localci-proxy.artemis.cit.tum.de.privkey.pem
    default_server: false

redirects:
  - name: "_"
    ssl_certificate_path: /var/lib/rbg-cert/live/host:f:artemis-staging-localci-proxy.artemis.cit.tum.de.fullchain.pem
    ssl_certificate_key_path: /var/lib/rbg-cert/live/host:f:artemis-staging-localci-proxy.artemis.cit.tum.de.privkey.pem
    default_server: true
    to: "{{ artemis_server_url }}"

firewall_hostgroup: default
proxy_forward_ssh: true
