---
##############################################################################
# TUM LocalVC Jenkins Stateless Configuration
##############################################################################

version_control:
  localvc:
    url: "{{ artemis_server_url }}"
    build_agent_git_credentials:
      user: "{{ lookup('hashi_vault', 'kv/data/artemis/common/jenkins-test').get('artemis-build-agent-git-username') }}"
      password: "{{ lookup('hashi_vault', 'kv/data/artemis/common/jenkins-test').get('artemis-build-agent-git-password') }}"

continuous_integration:
  jenkins_stateless:
    url: "https://artemis-jenkins-connector.artemis.cit.tum.de"
    artemis_auth_token_value: "{{ lookup('hashi_vault', 'kv/data/artemis/common/jenkins-test').get('artemis-authentication-token-value') }}"
