---
- name: Setup Artemis Load Balancer / Reverse Proxy
  hosts: artemis_production_proxy
  pre_tasks:
    - name: Install certbot nginx plugin
      ansible.builtin.package:
        name: python3-certbot-nginx
        state: present
      tags: certbot
      become: true

  roles:
    - role: geerlingguy.certbot
      become: true
      tags: certbot
      vars:
        certbot_auto_renew: true
        certbot_auto_renew_hour: "3"
        certbot_auto_renew_minute: "30"
        certbot_auto_renew_user: root
        certbot_auto_renew_options: "--quiet"
        certbot_create_if_missing: true
        certbot_admin_email: "{{ artemis_email }}"
        certbot_certs:
          - domains: "{{ (servers | map(attribute='name') | map('split', ' ') | flatten | list) + (redirects | map(attribute='name') | map('split', ' ') | flatten | list) }}"
        certbot_create_standalone_stop_services:
        certbot_create_command: "{{ certbot_script }} certonly --nginx --noninteractive --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }}"

    - role: ls1intum.artemis.firewall
      tags: firewall
      vars:
        firewall_hostgroup: proxy

    - role: ls1intum.artemis.proxy
      vars:
        proxy_available_nodes:
          - hostname: "[fcfe::a:1]"
            weight: 3
          - hostname: "[fcfe::a:2]"
            weight: 1
          - hostname: "[fcfe::a:3]"
            weight: 1
          - hostname: "[fcfe::a:4]"
            weight: 1
