---
- name: Start Artemis service on primary node
  hosts: artemis-production-node1.artemis.in.tum.de
  tasks:
    - name: Start artemis service
      become: true
      ansible.builtin.service:
        name: artemis
        state: started
    - name: Wait for 20 sec
      ansible.builtin.pause:
        seconds: 20

- name: Start Artemis service on all other nodes
  hosts: artemis_production_nodes
  serial: 1
  tasks:
    - name: Wait for 3 sec
      ansible.builtin.pause:
        seconds: 3

    - name: Start artemis service
      become: true
      ansible.builtin.service:
        name: artemis
        state: started
