---
- name: Setup Cluster Network and Forward Proxy
  hosts: artemis_production:!artemis_production_proxy:!artemis_production_nodes_ls1

  roles:
    - role: mrlesmithjr.netplan
      netplan_configuration:
        network:
          version: 2
          ethernets:
            ens192:
              addresses:
                - "{{ wireguard_host_ipv6_address }}/64"
                - "{{ host_ipv4_address }}/25"
              nameservers:
                addresses:
                  - 131.159.254.1
                  - 131.159.254.2
              routes:
                - to: 172.16.0.0/12
                  via: 172.24.70.126
                - to: 131.159.0.0/16
                  via: 172.24.70.126
                - to: default
                  via: 172.24.70.122

    - role: tomereli.proxy
      http_proxy: "http://proxy.in.tum.de:8080"
      https_proxy: "http://proxy.in.tum.de:8080"
      become: true

#- name: Setup Cluster Network LS1 VMs
#  hosts: artemis_production_nodes_ls1
#
#  roles:
#    - role: mrlesmithjr.netplan
#      netplan_configuration:
#        network:
#          version: 2
#          ethernets:
#            ens18:
#              addresses:
#                - "{{ wireguard_host_ipv6_address }}/64"
#                - "{{ host_ipv4_address }}"
#              nameservers:
#                addresses:
#                  - 131.159.254.1
#                  - 131.159.254.2
#              routes:
#                - to: 172.16.0.0/12
#                  via: 172.24.70.126
#                - to: 131.159.0.0/16
#                  via: 172.24.70.126
#                - to: default
#                  via: 172.24.70.122
#
#    - role: tomereli.proxy
#      http_proxy: "http://proxy.in.tum.de:8080"
#      https_proxy: "http://proxy.in.tum.de:8080"
#      become: true

- name: Setup Proxy Network
  hosts: artemis_production_proxy

  roles:
    - role: mrlesmithjr.netplan
      netplan_configuration:
        network:
          version: 2
          ethernets:
            ens224:
              dhcp4: true

              dhcp6: true

              routes:
                - to: default
                  via: 131.159.89.254
                - to: default
                  via: 2a09:80c0:89:1::ffff:1

              addresses:
                - "131.159.89.175/25"
                - "2a09:80c0:89:1::47/64"
            ens192:
              dhcp4: false
              dhcp6: false
              dhcp4-overrides:
                use-routes: false
              dhcp6-overrides:
                use-routes: false

              addresses:
                - "{{ wireguard_host_ipv6_address }}/64"
                - "{{ host_ipv4_address }}/25"
