---
- name: Stop Artemis service on secondary nodes
  hosts: artemis_production_nodes:!node1.prod.artemis.cit.tum.de
  tasks:
    - name: Stop artemis service
      become: true
      ansible.builtin.service:
        name: artemis
        state: stopped
