---

- name: Stop Artemis service on secondary nodes
  hosts: artemis_production_nodes:!artemis-production-node1.artemis.in.tum.de
  tasks:
    - name: Stop artemis service
      become: true
      ansible.builtin.service:
        name: artemis
        state: stopped
