---


- name: Setup Cluster Network and Forward Proxy
  hosts: artemis_production:!artemis-production-proxy.artemis.in.tum.de:!artemis_production_nodes_ls1

  roles:
    - role: mrlesmithjr.netplan
      netplan_configuration:
        network:
          version: 2
          ethernets:
            ens192:
              addresses:
                - "{{ wireguard_host_ipv6_address }}/64"
                - "{{ host_ipv4_address }}"
              nameservers:
                addresses:
                  - 131.159.254.1
                  - 131.159.254.2
              routes:
                - to: 172.16.0.0/12
                  via: 172.24.70.126
                - to: 131.159.0.0/16
                  via: 172.24.70.126
                - to: default
                  via: 172.24.70.122

    - role: tomereli.proxy
      http_proxy: "http://proxy.in.tum.de:8080"
      https_proxy: "http://proxy.in.tum.de:8080"
      become: true

- name: Setup Cluster Network LS1 VMs
  hosts: artemis_production_nodes_ls1

  roles:
    - role: mrlesmithjr.netplan
      netplan_configuration:
        network:
          version: 2
          ethernets:
            ens18:
              addresses:
                - "{{ wireguard_host_ipv6_address }}/64"
                - "{{ host_ipv4_address }}"
              nameservers:
                addresses:
                  - 131.159.254.1
                  - 131.159.254.2
              routes:
                - to: 172.16.0.0/12
                  via: 172.24.70.126
                - to: 131.159.0.0/16
                  via: 172.24.70.126
                - to: default
                  via: 172.24.70.122

    - role: tomereli.proxy
      http_proxy: "http://proxy.in.tum.de:8080"
      https_proxy: "http://proxy.in.tum.de:8080"
      become: true

- name: Setup Proxy Network
  hosts: artemis-production-proxy.artemis.in.tum.de

  roles:
    - role: mrlesmithjr.netplan
      netplan_configuration:
        network:
          version: 2
          ethernets:
            ens192:
              dhcp4: true
              dhcp6: true
              addresses:
                - "131.159.89.175/25"
                - "2a09:80c0:89:1::47/64"
            ens224:
              addresses:
                - "{{ host_ipv4_address }}"
                - "{{ wireguard_host_ipv6_address }}/64"
