---
- name: Setup Artemis Broker and Registry
  hosts: artemis_production_broker

  roles:
    - role: ls1intum.artemis.broker

    - role: ls1intum.artemis.firewall
      tags: firewall
      vars:
        firewall_hostgroup: default
