---
roles:
  - src: geerlingguy.docker

  - src: geerlingguy.mysql
    version: 5.0.1

  - src: geerlingguy.postgresql

  - src: mrlesmithjr.nfs-server

  - src: mrlesmithjr.netplan

  - src: tomereli.proxy

collections:
  - name: https://github.com/ls1intum/artemis-ansible-collection.git
    type: git
    version: redis-support
