---
- name: Setup Cluster Network
  hosts: artemis_dev_cluster

  roles:
    - role: ls1intum.artemis.wireguard
      become: true
      vars:
        wireguard_hostgroup: "{{ groups.artemis_dev_cluster }}"
