---
- name: Deploy Hermes Prod
  hosts: hermes-prod.artemis.cit.tum.de

  roles:
    - role: ls1intum.artemis.hermes
      vars:
        setup_system: false
        hermes_working_directory: /opt/hermes
