---
- name: Setup
  hosts: artemis_staging_localci_db

  roles:
    - role: geerlingguy.mysql
      become: true

    - role: ls1intum.artemis.mysqld_exporter
      become: true

    - role: ls1intum.artemis.firewall
      tags: firewall
