---

- name: Setup Artemis Nodes
  hosts: artemis_staging_localci_nodes

  roles:
    - role: ls1intum.artemis.storage_client
      tags:
        - storage
      # NFS should only be mounted on the core nodes
      when: inventory_hostname in groups['artemis_staging_localci_nodes_core']

    - role: ls1intum.artemis.artemis
      tags:
        - artemis

    - role: ls1intum.artemis.firewall
      tags: firewall
      vars:
        firewall_hostgroup: nodes

    - role: ls1intum.artemis.legal
      tags: legal
