---
- name: Start Artemis service
  hosts: artemis_staging_localci_nodes
  serial: 1
  tasks:
    - name: Start artemis service
      become: true
      ansible.builtin.service:
        name: artemis
        state: started

    - name: Wait for 20 seconds
      ansible.builtin.pause:
        seconds: 20
