---
- name: Setup Artemis Registry
  hosts: artemis_staging_localci_registry

  roles:
    - role: ls1intum.artemis.registry

    - role: ls1intum.artemis.proxy
      tags: proxy
      vars:
        proxy_forward_ssh: false
        proxy_generate_dh_param: false
        proxy_ssl_certificate_path: "/var/lib/rbg-cert/live/host:f:{{ inventory_hostname }}.fullchain.pem"
        proxy_ssl_certificate_key_path: "/var/lib/rbg-cert/live/host:f:{{ inventory_hostname }}.privkey.pem"
        proxy_target_port: 8761

    - role: ls1intum.artemis.firewall
      tags: firewall
      vars:
        firewall_hostgroup: registry
