---
- name: Setup Cluster Network
  hosts: artemis_staging_localci

  roles:
    - role: ls1intum.artemis.wireguard
      become: true
      vars:
        wireguard_hostgroup: "{{ groups.artemis_staging_localci }}"
