---
- name: Migration tester
  hosts: artemis-test-migration.artemis.cit.tum.de

  roles:
    - role: ls1intum.artemis.migration_tester
      become: true
      vars:
        dump_src: "~/artemis_backup.sql.gz"
        bake: true
