---
# IPv6 address (with CIDR!) which can be used to access the node - If left blank, ansible will use host facts to fill the address.
wireguard_host_ipv6_address: 2a09:80c0:ac18:4600::65
host_ipv4_address: 172.24.70.65
# Address of the node inside the network.
wireguard_interface_address: "fcfe:0:0:0:0:0:affe:9"

# Wireguard Keys - Autmatically generated!
wireguard_pubkey: sB2sqVW5RAbyXE2EqQYjenUIZjUNS87gE6z1FujAcnE=
wireguard_privkey: "{{ lookup('hashi_vault', 'kv/data/artemis/production/nodes').get('wg_priv_agent09') }}"

node_id: 1009
node_short_name: artemis-build-agent-9
node_display_name: Artemis Build Agent 9
