---
# IPv6 address (with CIDR!) which can be used to access the node - If left blank, ansible will use host facts to fill the address.
wireguard_host_ipv6_address: 2a09:80c0:ac18:4600::60
host_ipv4_address: 172.24.70.60
# Address of the node inside the network.
wireguard_interface_address: "fcfe:0:0:0:0:0:affe:4"

# Wireguard Keys - Autmatically generated!
wireguard_pubkey: 4gu0A3qyuQImDJkYU2FPluTWIZP0RbKWKbjqC7Jqdhk=
wireguard_privkey: "{{ lookup('hashi_vault', 'kv/data/artemis/production/nodes').get('wg_priv_agent04') }}"

node_id: 1004
node_short_name: artemis-build-agent-4
node_display_name: Artemis Build Agent 4
