---
# IPv6 address (with CIDR!) which can be used to access the node - If left blank, ansible will use host facts to fill the address.
wireguard_host_ipv6_address: 2a09:80c0:ac18:4600::76
host_ipv4_address: 172.24.70.76
# Address of the node inside the network.
wireguard_interface_address: "fcfe:0:0:0:0:0:affe:20"

# Wireguard Keys - Autmatically generated!
wireguard_pubkey: LjaZKAEiIhnMnsgygAvmNUmhp304iIFXgNjG93Dxowk=
wireguard_privkey: "{{ lookup('hashi_vault', 'kv/data/artemis/production/nodes').get('wg_priv_agent20') }}"

node_id: 1020
node_short_name: artemis-build-agent-20
node_display_name: Artemis Build Agent 20
