---
# IPv6 address (with CIDR!) which can be used to access the node - If left blank, ansible will use host facts to fill the address.
wireguard_host_ipv6_address: 2a09:80c0:ac18:4600::66
host_ipv4_address: 172.24.70.66
# Address of the node inside the network.
wireguard_interface_address: "fcfe:0:0:0:0:0:affe:10"

# Wireguard Keys - Autmatically generated!
wireguard_pubkey: t3TTtU0e/In2svE7mivN5uhGTKHqCF9dpIZoFlFiUUA=
wireguard_privkey: "{{ lookup('hashi_vault', 'kv/data/artemis/production/nodes').get('wg_priv_agent10') }}"

node_id: 1010
node_short_name: artemis-build-agent-10
node_display_name: Artemis Build Agent 10
