---
# IPv6 address (with CIDR!) which can be used to access the node - If left blank, ansible will use host facts to fill the address.
wireguard_host_ipv6_address: 2a09:80c0:ac18:4600::64
host_ipv4_address: 172.24.70.64
# Address of the node inside the network.
wireguard_interface_address: "fcfe:0:0:0:0:0:affe:8"

# Wireguard Keys - Autmatically generated!
wireguard_pubkey: Eh1HoONogtFw8nUQ8orIJFILRVQtq41jGyozyosgmCE=
wireguard_privkey: "{{ lookup('hashi_vault', 'kv/data/artemis/production/nodes').get('wg_priv_agent08') }}"

node_id: 1008
node_short_name: artemis-build-agent-8
node_display_name: Artemis Build Agent 8
