---
# IPv6 address (with CIDR!) which can be used to access the node - If left blank, ansible will use host facts to fill the address.
wireguard_host_ipv6_address: 2a09:80c0:ac18:4600::47
host_ipv4_address: 172.24.70.47
# Address of the node inside the network.
wireguard_interface_address: "fcfe:0:0:0:0:0:f:1"

# Wireguard Keys - Autmatically generated!
wireguard_pubkey: wW5mj7uqEqWPN/kzRCKkx88TodVL+JhfFfpdqUG6vW8=
wireguard_privkey: "{{ lookup('hashi_vault', 'kv/data/artemis/production/nodes').get('wg_priv_proxy') }}"
