---
# IPv6 address (with CIDR!) which can be used to access the node - If left blank, ansible will use host facts to fill the address.
wireguard_host_ipv6_address: "2a09:80c0:ac18:4680::2"

# Address of the node inside the network.
wireguard_interface_address: "fcfe:0:0:0:0:0:f:1"

# Wireguard Keys - Autmatically generated!
wireguard_pubkey: /kPBWHT2Dyc7lGAuM5Zp+pYN/S6JxX5R5Vtejr5ZdQo=
wireguard_privkey: "{{ lookup('hashi_vault', 'kv/data/artemis/test/staging-localci').get('wg_priv_proxy') }}"

# IPv4 Host address as a workaround for LS1ADMIN-37679 (Netzwerk-Config von Staging Local fixen)
host_ipv4_address: "172.24.70.188/25"
