# IPv6 address (with CIDR!) which can be used to access the node - If left blank, ansible will use host facts to fill the address.
wireguard_host_ipv6_address: "2a09:80c0:ac18:4600::34"

# Address of the node inside the network.
wireguard_interface_address: "fcfe:0:0:0:0:0:affe:23"

# Wireguard Keys - Autmatically generated!
wireguard_pubkey: 7mvKzq4RiQ51Vz6W7QcNmi2t5/wBGJ69dmW8ystfTj4=
wireguard_privkey: "{{ lookup('hashi_vault', 'kv/data/artemis/production/nodes').get('wg_priv_agent23') }}"

host_ipv4_address: 172.24.70.34/25

node_id: 123

node_short_name: artemis-build-agent-large-11
node_display_name: Artemis Build Agent Large 11
