---
# IPv6 address (with CIDR!) which can be used to access the node - If left blank, ansible will use host facts to fill the address.
wireguard_host_ipv6_address: "2a09:80c0:ac18:4680::5"

# Address of the node inside the network.
wireguard_interface_address: "fcfe:0:0:0:0:0:d:1"

# Wireguard Keys - Autmatically generated!
wireguard_pubkey: EOzVHjgqbOQ6eqyy0EQCQiZ1s5eg++91OXtNdOnL1AE=
wireguard_privkey: "{{ lookup('hashi_vault', 'kv/data/artemis/test/staging-localci').get('wg_priv_db') }}"

# IPv4 Host address as a workaround for LS1ADMIN-37679 (Netzwerk-Config von Staging Local fixen)
host_ipv4_address: "172.24.70.133/25"
