# IPv6 address (with CIDR!) which can be used to access the node - If left blank, ansible will use host facts to fill the address.
wireguard_host_ipv6_address: "2a09:80c0:ac18:4600::2"

# Address of the node inside the network.
wireguard_interface_address: "fcfe:0:0:0:0:0:a:9"

# Wireguard Keys - Autmatically generated!
wireguard_pubkey: P2N0NGKZc4TOT4UozxVM+eR0Ru/u1AiKf1wSO84ibSk=
wireguard_privkey: "{{ lookup('hashi_vault', 'kv/data/artemis/production/nodes').get('wg_priv_node9') }}"

host_ipv4_address: "172.24.70.2/25"

node_id: 9

node_short_name: artemis-build-agent-large-1
node_display_name: Artemis Build Agent Large 1
