# IPv6 address (with CIDR!) which can be used to access the node - If left blank, ansible will use host facts to fill the address.
wireguard_host_ipv6_address: "2a09:80c0:ac18:4600::9"

# Address of the node inside the network.
wireguard_interface_address: "fcfe:0:0:0:0:0:affe:4"

# Wireguard Keys - Autmatically generated!
wireguard_pubkey: 4CN9QN+PV3m5rcjy46VUrJhqzV+dmGiVmUkzsNXJmRQ=
wireguard_privkey: "{{ lookup('hashi_vault', 'kv/data/artemis/production/nodes').get('wg_priv_agent4') }}"

host_ipv4_address: 172.24.70.9/25

node_id: 104

node_short_name: artemis-build-agent-small-4
node_display_name: Artemis Build Agent Small 4
