# IPv6 address (with CIDR!) which can be used to access the node - If left blank, ansible will use host facts to fill the address.
wireguard_host_ipv6_address: "2a09:80c0:ac18:4600::41"

# Address of the node inside the network.
wireguard_interface_address: "fcfe:0:0:0:0:0:affe:27"

# Wireguard Keys - Autmatically generated!
wireguard_pubkey: i0TRI68yobRzhYjbwD+8W5fYgi+ivc+blo/xnFJzpSw=
wireguard_privkey: "{{ lookup('hashi_vault', 'kv/data/artemis/production/nodes').get('wg_priv_agent27') }}"

host_ipv4_address: 172.24.70.41/25

node_id: 127

node_short_name: artemis-build-agent-large-15
node_display_name: Artemis Build Agent Large 15
