---
# IPv6 address (with CIDR!) which can be used to access the node - If left blank, ansible will use host facts to fill the address.
wireguard_host_ipv6_address: "2a09:80c0:ac18:4600::20"

# Address of the node inside the network.
wireguard_interface_address: "fcfe:0:0:0:0:0:d:1"

# Wireguard Keys - Autmatically generated!
wireguard_pubkey: FOffCDVijIfWidUJWk5ZLtJaLcMrzCH7QG9cZZ3WARo=
wireguard_privkey: "{{ lookup('hashi_vault', 'kv/data/artemis/production/nodes').get('wg_priv_db') }}"

host_ipv4_address: "172.24.70.20/25"
