---
# IPv6 address (with CIDR!) which can be used to access the node - If left blank, ansible will use host facts to fill the address.
wireguard_host_ipv6_address: "2a09:80c0:ac18:4680::1"
host_ipv4_address: 172.24.70.129/25

# Address of the node inside the network.
wireguard_interface_address: "fcfe:0:0:0:0:0:f:1"

# Wireguard Keys - Autmatically generated!
wireguard_pubkey: ZdqCmvY4aLuP5f3R7YUMnGxRGUk05i+43x7UG4K45lI=
wireguard_privkey: "{{ lookup('hashi_vault', 'kv/data/artemis/test/staging1').get('wg_privkey_proxy') }}"
