---
- name: Setup Artemis Nodes
  hosts: artemistests artemis_staging1_nodes artemis_staging2_nodes artemis_production_nodes

  roles:
    - role: ls1intum.artemis.artemis
      vars:
        artemis_force_no_restart: true
        only_update_artemis_config: true
